version: 2
registries:
  maven-codeartifact:
    type: maven-repository
    url: https://getyourguide-130607246975.d.codeartifact.eu-central-1.amazonaws.com/maven/private/
    username: "aws"
    password: "${{secrets.CODEARTIFACT_AUTH_TOKEN}}"
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
  # Enable version updates for gradle
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      day: sunday
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    registries:
      - maven-codeartifact
